### ISSUE TITLE
Q: how to connect wallet connect on dev on simulator?

### ISSUE THREAD

**Issue by bidah** [cawfree/create-react-native-dapp#15]
I'm submitting a ...
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[x] question about how to use this project

Summary

I can't found out how to get wallet connect working on dev env. I am on the simulator but when opening wallet popup you need to have an app like metamask mobile connected but you can't install apps in the simulator. How can I make the connection on dev?

Other information (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by cawfree** [comment]
Hi @bidah, thanks for getting in touch! There are a few ways you could accomplish this:
  - Use `yarn web`/`npm run-script web` to run the version of your app within a browser and scan the QR code shown on your browser using a physical device.
  - Build [__Rainbow__](https://github.com/rainbow-me/rainbow) from source and install this on your emulator.
  - Render [the WalletConnect QR Code](Connect/walletconnect-monorepo/blob/v1.0/packages/helpers/react-native-dapp/src/components/Qrcode.tsx) in your development environment on mobile and scan this with another device (`uri` in this instance is the WalletConnect URI).
 
You can also avoid using WalletConnect in dev and just allocate a hot wallet programmatically stored with initial funds to play with (this is what the example application does). This is only really useful for testing on-chain interactions though, since it basically ignores the connection flow the user would be required to work through.
