### ISSUE TITLE
yarn ios completes with "nothing to compile"

### ISSUE THREAD

**Issue by zkhalapyan** [cawfree/create-react-native-dapp#17]
- **I'm submitting a ...**
  [ X ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Following the exact step by step guidelines on the readme page;  yarn ios just ends with "nothing to compile" and doesn't open any apps. 

You can actually call `npm start` and this will go with the launch sequence, but will show a blank page on Expo Go. 

What's the appropriate command to run? 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by cawfree** [comment]
Hello, are you trying to open the application in Expo Go?

I think the message `nothing to compile` comes from Hardhat, indicating that your contracts have already been compiled, so this is probably a red herring.

**Comment by zkhalapyan** [comment]
Not sure what was going on, calling `yarn ios` now works 🤷‍♂️ I lost track of the sequence of things I tried, but I bet if you start from a clean init, you would hit the same problem. I am using Xcode 13 by the way, seems like they deprecated instruments and that's causing more RN problems right now.

**Comment by cawfree** [comment]
I'm going to close this issue because issues with launching is related to #19 (incompatibility with Expo Go) and I'd like to maintain the discussion there.

Just to clarify, the `contracts/` directory is compiled when the project is first bootstrapped, so it is perfectly normal to see `nothing to compile` since we attempt to recompile whenever the application is launched.

This message is not associated with any of the behaviour in React Native.
