### ISSUE TITLE
How to run on iOS device?

### ISSUE THREAD

**Issue by zkhalapyan** [cawfree/create-react-native-dapp#18]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [X] question about how to use this project

- **Summary**

Calling `yarn ios` opens the app in simulator. Can we update the docs on running it on device?

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

I will follow up here as I discover the right set of commands.

**Comment by zkhalapyan** [comment]
Was able to run it through building via Xcode. 

1. Run `yarn ios`, it will open in sim; kill it. 
2. Go to `./ios/project.xcworkspace`, open it; set the team and run on device. 
3. If you see a blank screen, make sure that both device & computer are on the same WiFi network. 

So this specifically is not using Expo; expo is only for running on Expo Go. 

Some requests for clarification: 

* Readme says the project is using Expo, but the launch instructions are actually just regular RN. It leads towards confusion; if the project says it's using Expo, why isn't the launch command using Expo? 
* `yarn ios` only launches on sim, which is useless for testing out wallet login; can we please update to include the above instructions? Or is there a better way to run on device?

**Comment by cawfree** [comment]
The project is bootstrapped using Expo, meaning it supports unimodules. We do however depend upon some native compilation changes, but it doesn't stop you from taking advantage of their awesome stack. With respect to #19, the reason you'll be receiving that error is because launching the application directly via XCode will not start the hardhat node. You could add this as a [__Script Phase__](https://stackoverflow.com/questions/39632301/where-is-the-run-script-and-build-phase-in-xcode) build step in your project configuration if you wished to emulate the functionality of `yarn ios`.

Work is currently in progress to prevent us from having to depend upon Expo eject, which would allow you to easily view the app in Expo Go. Until this is resolved we must depend upon compiled binaries which limits our compatibility.

There are a couple of workarounds for connecting to a wallet if you're running on a simulator. You can:
  - Test connection on the using web `yarn web`.
  - Compile [__Rainbow__](https://github.com/rainbow-me/rainbow) from source and use this on the simulator.
  - Allocate a hot wallet (the `HARDHAT_PRIVATE_KEY` environment variable is initialized with a simulated balance of 100 ETH) and use this to experiment with transactions etc.

**Comment by zkhalapyan** [comment]
So is there no way to run on device via `yarn ios`? It currently defaults to simulator, and I haven't found a way to change it.
