### ISSUE TITLE
Only seeing splashscreen on expo

### ISSUE THREAD

**Issue by DeveloperAlly** [cawfree/create-react-native-dapp#9]
- **I'm submitting a ...**
  [ x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I got this running using `npm install --legacy-peer-deps` after running `npx create-react-native-dapp`
Then I modified index.js from `const { default: App } = require("./frontend/App");` to `const { default: App } = require("./App");`
Then  I ran `expo start` (while logged into expo-cli) to start the app.

It runs, but I only see the ethereum logo splash screen and not the App.tsx code on both my android phone expo app and ios simulator on mac, rather than the App page.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

I note that npx create-react-native-dapp throws an error when run too - will find the log

Also running expo start gives me a warning
```
`Opening developer tools in the browser...
Some dependencies are incompatible with the installed expo package version:
 - react-native-get-random-values - expected version: ~1.7.0 - actual version installed: 1.5.0
Your project may not work correctly until you install the correct versions of the packages.
To install the correct versions of these packages, please run: expo install [package-name ...]`
```

Interestingly I see the App.tsx screen in the web version and also if I use `expo run:ios` to build then run this on ios emulator in mac.

Also for the error above - if I do update the pacakage to the ~1.7.0 version expo wants I get ->
```
Building JavaScript bundle: error
Error
19:20
Unable to resolve module ./getRandomBase64 from ".."

None of these files exist:
  * node_modules/react-native-get-random-values/getRandomBase64(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
  * node_modules/react-native-get-random-values/getRandomBase64/index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
> 1 | const base64Decode = require('fast-base64-decode')
  2 | const { NativeModules } = require('react-native')
  3 |
  4 | class TypeMismatchError extends Error {}
```

Any help would be appreciated and thanks for all the awesome work on this package

Thanks!

**Comment by DeveloperAlly** [comment]
Nevermind - I installed it without the typescript dependency and now seeing the correct screen!

Thankyou for this awesome package!

**Comment by DeveloperAlly** [comment]
Actually this problem persists any thoughts?

**Comment by cawfree** [comment]
Hey @DeveloperAlly, my apologies for the delay getting back to you.  🙏

Thanks for your detailed bug report!

It sounds like you needed to make a lot of manual changes to get this "working", which suggests to me that the project did not initialize properly! Just so I'm not misunderstanding, can you please clarify; without making any changes to the project, did commands like `npm run-script ios` or `npm run-script web` start the application correctly? If these did work after calling `npx create-react-native-dapp`, can you provide the reasoning behind having to modify the `index.js`? Having to change the path of the import location suggests that `npx create-react-native-dapp` did not terminate successfully.

If you can see the text `"Welcome to React Native"` on the iOS Simulator after running `npm run-script ios`, this would be an indication that everything is working (since this text is driven by the deployment and interaction with a contract on a simulated blockchain on your localhost). Using a command like `expo start` will __not__ start this project correctly because it will not manage deployment of the chain, and since we've applied native changes we will not be able to view the project inside [Expo Go](https://expo.io/client).

I noticed your activity in [this other issue](https://github.com/cawfree/create-react-native-dapp/issues/7); having to run `npx create-react-native-dapp` with this additional flag suggests to me the development environment is not properly configured. What version of `expo-cli` are you currently running?
